# Generated by Django 3.1.5 on 2021-01-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20210124_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
