# Generated by Django 3.1.5 on 2021-01-25 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0004_remove_projects_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('bio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
